name: Update Portfolio Projects

on:
  schedule:
    # Roda todo dia à meia-noite (UTC)
    - cron: '0 0 * * *'
  # Permite rodar manualmente na aba "Actions" do GitHub
  workflow_dispatch:

jobs:
  update_database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Import Command
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          # Adicione outras variáveis de ambiente necessárias aqui (ex: DATABASE_URL)
        run: |
          python manage.py import_github IsaPotter